engines:
  shellcheck:
    enabled: true
      checks:
        SC2016:
          enabled: false
ratings:
  paths:
  - "webera"
  - "tests/helper"
  - "tests/test-*"
  - "examples/generate"
exclude_paths:
  - "**/extern/"
