sudo: false
language: generic

matrix:
  include:

      # Ubuntu Precise
    - os: linux
      dist: precise
      sudo: false

      # Ubuntu 14.04.4 LTS (Trusty Tahr)
    - os: linux
      dist: trusty
      sudo: false

      # OS X 10.12
    - os: osx
      osx_image: xcode8.2

  fast_finish: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/dupes; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bash coreutils gnu-sed grep gawk; fi

script:
  - ./webera --version
  - ./tests/helper --run-all
